Nada darwinia parachain bridger
darwinia-network/indexer pull request #101
Opened 2022-11-03 13:29 UTC by furoxr

- [x] Darwinia subql for Darwinia-Parachain
- [x] Darwinia-Parachain subql for Darwinia
- [x] Polkdot subxt for Darwinia-Parachain

2022-11-14 03:41 UTC, fewensa requested changes

2022-11-14 03:41 UTC, fewensa commented on subql/packages/bridger/yarn.lock
> +"@darwinia/index-common@*":
Maybe we don't need update this.

2022-11-17 14:56 UTC, furoxr commented on subql/packages/bridger/project/darwinia-parachain.yaml
> +  chainId: '0xe71578b37a7c799b0ab4ee87ffa6f059a6b98f71f06fb8c84a8d88013a548ad6'
The block hash at block 0 is `0xe71578b37a7c799b0ab4ee87ffa6f059a6b98f71f06fb8c84a8d88013a548ad6`, according to this: https://darwinia-parachain.subscan.io/block/0

2022-12-20 03:03 UTC, fewensa commented
We don't need this now.

2022-12-20 03:03 UTC, closed without merging